api = "0.6"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/dotnet-execute"
  id = "paketo-buildpacks/dotnet-execute"
  name = "Paketo .NET Execute Buildpack"
  version = "{{ .Version }}"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
